"""empty message

Revision ID: 966c03e030d6
Revises: 6d082c34565f
Create Date: 2022-05-21 14:54:12.612150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966c03e030d6'
down_revision = '6d082c34565f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
