"""empty message

Revision ID: f5c1e916f922
Revises: b3ad81d1781b
Create Date: 2022-05-25 04:20:30.141489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5c1e916f922'
down_revision = 'b3ad81d1781b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    type_=postgresql.ARRAY(sa.String()),
                    nullable=False, postgresql_using='genres::character varying[]')
    op.alter_column('Venue', 'genres',
                    existing_type=sa.VARCHAR(),
                    type_=postgresql.ARRAY(sa.String()),
                    nullable=False, postgresql_using='genres::character varying[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
                    existing_type=postgresql.ARRAY(sa.String()),
                    type_=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Artist', 'genres',
                    existing_type=postgresql.ARRAY(sa.String()),
                    type_=sa.VARCHAR(length=120),
                    nullable=True)
    # ### end Alembic commands ###
